# .github/workflows/deploy.yml
name: NestJS Prod CD Pipeline

on:
  push:
    branches: ['main'] # main 브랜치에 코드가 push될 때만 작동

jobs:
  deploy:
    runs-on: ubuntu-latest # GitHub이 제공하는 1회용 리눅스 서버에서 실행

    steps:
      - name: 🚀 디지털오션 서버 접속 및 자동 배포 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd univ-allinfo-nestjs || exit

            git pull origin main

            echo "${{ secrets.ENV_FILE }}" > .env

            # 1. 기존 컨테이너 내리기 (프로덕션 파일명 명시)
            docker-compose -f docker-compose.prod.yml down

            # 2. 프로덕션 파일로 백그라운드 빌드 및 실행
            docker-compose -f docker-compose.prod.yml up --build -d

            # 3. 마이그레이션 실행
            docker-compose -f docker-compose.prod.yml exec -T api npm run migration:run

            # 4. 쓸모없는 더미 도커 이미지 청소
            docker image prune -f
